# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnUAOghQwMpyGmNYJDpo3_2mtOFWlDFV
"""

import random
import statistics

BLOCK_SIZE = 100

def generate_sensor_data():

    # Generate missing samples
    if random.random() < 0.05:
        return None

    # Generate corrupted samples
    if random.random() < 0.05:
        return random.randint(101, 150)

    # Generate valid samples
    return random.randint(0, 100)

def process_block(block):

    valid_samples = []
    missing_count = 0
    corrupted_count = 0

    for sample in block:

        if sample is None:
            missing_count += 1

        elif sample < 0 or sample > 100:
            corrupted_count += 1

        else:
            valid_samples.append(sample)

    if len(valid_samples) > 0:

        maximum = max(valid_samples)
        minimum = min(valid_samples)
        average = statistics.mean(valid_samples)
        std_dev = statistics.stdev(valid_samples)

        print("\n----- Block Results -----")
        print("Maximum Value :", maximum)
        print("Minimum Value :", minimum)
        print("Average Value :", round(average, 2))
        print("Standard Deviation :", round(std_dev, 2))
        print("Missing Samples :", missing_count)
        print("Corrupted Samples :", corrupted_count)

    else:
        print("No valid samples found.")

def main():

    block = []

    for i in range(BLOCK_SIZE):

        sample = generate_sensor_data()
        block.append(sample)

    process_block(block)

if __name__ == "__main__":
    main()